name: FieldTrip
favicon: null
layout_spectrum: 0
typography_spectrum: 0.78223
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#0b233d'
    - '#4fafbd'
    - '#306a78'
    - '#d78860'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
