name: FieldTrip
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#0b233d'
    - '#4fafbd'
    - '#306a78'
    - '#d78860'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
