favicon: null
name: FieldTrip
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5143369
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#000002'
    - '#0b233d'
    - '#4fafbd'
    - '#306a78'
    - '#d78860'
  rhythmicContrast: 0.5
typography_spectrum: 0.48768
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
